name: display secret value

on:
  workflow_dispatch:

jobs:
  echo-value:
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
