name: display secret value

on:
  workflow_dispatch:

jobs:
  echo-value:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
